import { useEffect } from "react";
import { AnimatePresence, motion } from "motion/react";
import { Check, Play, Plus, ThumbsUp, Volume2, X } from "lucide-react";
import { useApp } from "@/components/AppProvider";
import { imageUrl, mediaTitle, mediaYear } from "@/lib/utils";
import type { MediaItem } from "@/types/media";

const genres: Record<number, string> = { 12: "Adventure", 16: "Animation", 18: "Drama", 27: "Horror", 28: "Action", 35: "Comedy", 36: "History", 53: "Thriller", 80: "Crime", 99: "Documentary", 878: "Sci-Fi", 9648: "Mystery", 10759: "Action & Adventure" };

export function InfoModal({ catalog }: { catalog: MediaItem[] }) {
  const { selectedMedia: media, closeMedia, myList, toggleList, openMedia } = useApp();
  useEffect(() => { document.body.style.overflow = media ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [media]);
  const similar = media ? catalog.filter((item) => item.id !== media.id && item.genre_ids.some((id) => media.genre_ids.includes(id))).slice(0, 6) : [];
  return <AnimatePresence>{media && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={(e) => e.target === e.currentTarget && closeMedia()} className="fixed inset-0 z-50 overflow-y-auto bg-black/75 px-0 py-0 backdrop-blur-sm sm:px-6 sm:py-12"><motion.div role="dialog" aria-modal="true" aria-label={`${mediaTitle(media)} details`} initial={{ y: 60, scale: .96 }} animate={{ y: 0, scale: 1 }} exit={{ y: 50, scale: .97 }} transition={{ type: "spring", damping: 26, stiffness: 260 }} className="modal-scroll relative mx-auto min-h-screen max-w-4xl overflow-hidden bg-[#181818] shadow-2xl sm:min-h-0 sm:rounded-lg">
    <div className="relative aspect-[16/9] bg-cover bg-center" style={{ backgroundImage: `url(${imageUrl(media.backdrop_path, "original")})` }}><div className="absolute inset-0 bg-gradient-to-t from-[#181818] via-transparent to-black/15" /><button onClick={closeMedia} className="absolute right-4 top-4 z-10 grid size-9 place-items-center rounded-full bg-[#181818] hover:bg-[#333]" aria-label="Close"><X className="size-5" /></button><button className="absolute right-4 top-1/2 grid size-9 place-items-center rounded-full border-2 border-white/60 bg-black/30 hover:border-white" aria-label="Volume"><Volume2 className="size-4" /></button><div className="absolute bottom-7 left-5 right-5 sm:left-12"><h2 className="max-w-xl text-3xl font-black tracking-tight drop-shadow-xl sm:text-5xl">{mediaTitle(media)}</h2><div className="mt-5 flex items-center gap-2"><button className="flex items-center gap-2 rounded bg-white px-6 py-2.5 font-bold text-black hover:bg-[#ddd]"><Play className="size-5 fill-current" /> Play</button><button onClick={() => toggleList(media.id)} className="grid size-10 place-items-center rounded-full border-2 border-[#aaa] bg-black/25 hover:border-white">{myList.includes(media.id) ? <Check className="size-5" /> : <Plus className="size-5" />}</button><button className="grid size-10 place-items-center rounded-full border-2 border-[#aaa] bg-black/25 hover:border-white"><ThumbsUp className="size-5" /></button></div></div></div>
    <div className="grid gap-8 px-5 pb-10 pt-3 sm:grid-cols-[2fr_1fr] sm:px-12"><div><div className="flex flex-wrap items-center gap-2 text-sm"><span className="font-bold text-[#46d369]">{Math.min(98, Math.round(media.vote_average * 10))}% Match</span><span>{mediaYear(media)}</span><span className="border border-[#777] px-1.5">{media.adult ? "18+" : "13+"}</span><span>2h 18m</span><span className="rounded border border-[#777] px-1 text-[10px]">HD</span><span className="rounded border border-[#777] px-1 text-[10px]">4K</span></div><p className="mt-5 leading-relaxed text-[#e5e5e5]">{media.overview || "A captivating story of ambition, loyalty, and discovery that changes everything."}</p></div><div className="space-y-3 text-sm text-[#777]"><p>Cast: <span className="text-[#ddd]">Featured ensemble, award-winning performers</span></p><p>Genres: <span className="text-[#ddd]">{media.genre_ids.map((id) => genres[id]).filter(Boolean).join(", ") || "Drama, Adventure"}</span></p><p>This title is: <span className="text-[#ddd]">Emotional, Cinematic, Gripping</span></p></div></div>
    <div className="px-5 pb-12 sm:px-12"><h3 className="mb-5 text-xl font-bold">More Like This</h3><div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">{(similar.length ? similar : catalog.filter((item) => item.id !== media.id).slice(0, 6)).map((item) => <button key={item.id} onClick={() => openMedia(item)} className="overflow-hidden rounded bg-[#2f2f2f] text-left hover:-translate-y-1"><div className="relative aspect-video"><img src={imageUrl(item.backdrop_path)} alt={mediaTitle(item)} className="h-full w-full object-cover" /><span className="absolute bottom-2 right-2 rounded bg-black/75 px-1.5 py-1 text-[10px]">{Math.floor(90 + item.vote_average) }m</span></div><div className="p-3"><div className="flex items-center justify-between text-xs"><span className="font-bold text-[#46d369]">{Math.round(item.vote_average * 10)}% Match</span><span>{mediaYear(item)}</span></div><p className="mt-2 line-clamp-2 text-xs leading-relaxed text-[#bbb]">{item.overview}</p></div></button>)}</div></div>
  </motion.div></motion.div>}</AnimatePresence>;
}
