import { useRef, useState } from "react";
import { ChevronDown, ChevronLeft, ChevronRight, Check, Play, Plus, ThumbsUp } from "lucide-react";
import { motion } from "motion/react";
import { useApp } from "@/components/AppProvider";
import { imageUrl, mediaTitle, mediaYear } from "@/lib/utils";
import type { MediaItem } from "@/types/media";

function MovieCard({ media, rank }: { media: MediaItem; rank?: number }) {
  const { openMedia, myList, toggleList } = useApp();
  const listed = myList.includes(media.id);
  return <motion.article whileHover={{ y: -5 }} className="group relative w-[68vw] shrink-0 sm:w-[38vw] md:w-[29vw] lg:w-[22vw] xl:w-[18vw]"><button onClick={() => openMedia(media)} className="block w-full text-left"><div className="relative aspect-video overflow-hidden rounded bg-[#252525] shadow-md transition-all duration-300 group-hover:shadow-[0_14px_30px_rgba(0,0,0,.65)]"><img src={imageUrl(media.backdrop_path)} alt={mediaTitle(media)} loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" />{rank && <span className="absolute bottom-1 left-2 text-3xl font-black italic drop-shadow-[0_2px_5px_#000]">{rank}</span>}<div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 transition-opacity group-hover:opacity-100" /></div></button><div className="invisible absolute left-0 right-0 top-[calc(100%-2px)] z-20 rounded-b bg-[#181818] p-3 opacity-0 shadow-[0_16px_30px_rgba(0,0,0,.8)] transition-all duration-200 group-hover:visible group-hover:opacity-100"><div className="flex items-center gap-2"><button onClick={() => openMedia(media)} className="grid size-8 place-items-center rounded-full bg-white text-black hover:bg-[#ddd]" aria-label="Play"><Play className="size-4 fill-current" /></button><button onClick={() => toggleList(media.id)} className="grid size-8 place-items-center rounded-full border-2 border-[#888] hover:border-white" aria-label={listed ? "Remove from list" : "Add to list"}>{listed ? <Check className="size-4" /> : <Plus className="size-4" />}</button><button className="grid size-8 place-items-center rounded-full border-2 border-[#888] hover:border-white" aria-label="I like this"><ThumbsUp className="size-4" /></button><button onClick={() => openMedia(media)} className="ml-auto grid size-8 place-items-center rounded-full border-2 border-[#888] hover:border-white" aria-label="More information"><ChevronDown className="size-4" /></button></div><p className="mt-3 truncate text-sm font-semibold">{mediaTitle(media)}</p><div className="mt-2 flex items-center gap-2 text-[11px]"><span className="font-bold text-[#46d369]">{Math.min(98, Math.round(media.vote_average * 10))}% Match</span><span className="border border-[#777] px-1">{media.adult ? "18+" : "13+"}</span><span>{mediaYear(media)}</span><span className="border border-[#777] px-1 text-[9px]">HD</span></div></div></motion.article>;
}

export function MovieRow({ title, items, ranked = false }: { title: string; items: MediaItem[]; ranked?: boolean }) {
  const ref = useRef<HTMLDivElement>(null); const [position, setPosition] = useState(0);
  function scroll(direction: number) { const amount = ref.current?.clientWidth ?? 600; ref.current?.scrollBy({ left: direction * amount * .85, behavior: "smooth" }); setPosition((value) => Math.max(0, value + direction)); }
  return <section className="group/row relative mb-8 sm:mb-11"><div className="mb-3 flex items-center px-5 sm:px-[4vw]"><h2 className="text-lg font-bold sm:text-xl">{title}</h2><span className="ml-2 translate-x-[-8px] text-xs font-bold text-cyan-400 opacity-0 transition-all group-hover/row:translate-x-0 group-hover/row:opacity-100">Explore all ›</span></div><div className="relative"><button onClick={() => scroll(-1)} className={`absolute bottom-0 left-0 top-0 z-20 w-10 rounded-r bg-black/65 opacity-0 hover:bg-black/80 group-hover/row:opacity-100 sm:w-[4vw] ${position === 0 ? "pointer-events-none !opacity-0" : ""}`} aria-label="Previous titles"><ChevronLeft className="mx-auto size-8" /></button><div ref={ref} id={title === "My List" ? "my-list" : undefined} className="no-scrollbar flex gap-1.5 overflow-x-auto overflow-y-hidden px-5 pb-24 sm:gap-2 sm:px-[4vw]">{items.map((media, index) => <MovieCard key={`${title}-${media.id}-${index}`} media={media} rank={ranked && index < 10 ? index + 1 : undefined} />)}</div><button onClick={() => scroll(1)} className="absolute bottom-24 right-0 top-0 z-20 w-10 rounded-l bg-black/65 opacity-0 hover:bg-black/80 group-hover/row:opacity-100 sm:w-[4vw]" aria-label="Next titles"><ChevronRight className="mx-auto size-8" /></button></div></section>;
}
